DROP DATABASE bookapp_db;

CREATE DATABASE bookapp_db;

USE bookapp_db; 

DROP TABLE users;

CREATE TABLE users
(
 id INT PRIMARY KEY AUTO_INCREMENT,
 NAME VARCHAR(200) UNIQUE NOT NULL,
 email VARCHAR(200) NOT NULL,
 PASSWORD VARCHAR(200) NOT NULL
);

DROP TABLE books;

CREATE TABLE books
(
 id INT PRIMARY KEY AUTO_INCREMENT,
 NAME VARCHAR(200) NOT NULL,
 price FLOAT NOT NULL
);
 
DROP TABLE orders;

CREATE TABLE orders
(
 id INT PRIMARY KEY AUTO_INCREMENT,
 user_id INT,
 total_price FLOAT NOT NULL,
 ordered_date TIMESTAMP DEFAULT NOW(),
 modified_date TIMESTAMP DEFAULT NOW(),
 STATUS VARCHAR(50) DEFAULT 'ORDERED' 
 );

DROP TABLE carts;

CREATE TABLE carts
(
id INT PRIMARY KEY AUTO_INCREMENT,
user_id INT,
book_id INT,
quantity INT NOT NULL,
CONSTRAINT fk_users_id FOREIGN KEY(user_id) REFERENCES users(id)
);

INSERT INTO books VALUES(1,'Java',500);

INSERT INTO books VALUES(2,'C',500);

INSERT INTO books VALUES(3,'C++',500);


