DROP DATABASE bookapp_db;

CREATE DATABASE bookapp_db;

USE bookapp_db; 

DROP TABLE users;

CREATE TABLE users
(
 id INT PRIMARY KEY AUTO_INCREMENT,
 NAME VARCHAR(200) UNIQUE NOT NULL,
 email VARCHAR(200) NOT NULL,
 PASSWORD VARCHAR(200) NOT NULL
);

DROP TABLE books;

CREATE TABLE books
(
 id INT PRIMARY KEY AUTO_INCREMENT,
 NAME VARCHAR(200) NOT NULL,
 price FLOAT NOT NULL
);
 
DROP TABLE orders;

CREATE TABLE orders
(
 id INT PRIMARY KEY AUTO_INCREMENT,
 user_id INT,
 book_id INT,
 quantity INT NOT NULL,
 ordered_date TIMESTAMP DEFAULT NOW(),
 STATUS VARCHAR(50) DEFAULT 'ORDERED' ,
 CONSTRAINT fk_users_id FOREIGN KEY(user_id) REFERENCES users(id),
 CONSTRAINT fk_books_id FOREIGN KEY(book_id) REFERENCES books(id)
);



